# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David H Lee
tagline:          Python Web Developer
url:              http://davidhajoon.com
paginate:         1
baseurl:          http://davidhajoon.com
author:
  name:           David H Lee
  url:            https://twitter.com/fakdora
  email:          davidleesd@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           http://fakdora.github.io/poole/
