# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            David H Lee
tagline:          Python Web Developer
url:              http://davidhajoon.com/
paginate:         1
baseurl:          /
author:
  name:           David H Lee
  url:            https://twitter.com/fakdora
  email:          davidleesd@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           http://fakdora.github.io/poole/


# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
